### ISSUE TITLE
ha

### ISSUE THREAD

**Issue by hecker12423** [whitetrashyt/r34discordbot#11]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Python310\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Python310\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: object method can't be used in 'await' expression
 happens when you run porn command

**Comment by whitetrashyt** [comment]
Looking at this now, I have to reinstall python since I'm working on a new PC, but I'll get to work on it.

**Comment by whitetrashyt** [comment]
Fixed with the latest update. Let me know if you encounter any other issues.
