### ISSUE TITLE
&help command is broken

### ISSUE THREAD

**Issue by samalzpro49** [whitetrashyt/r34discordbot#13]
When i run &help the terminal sends an error
this is what i get

>2023-11-21 07:32:58 INFO     discord.client logging in using static token
2023-11-21 07:32:59 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 30866d99caba29ce499f5c8632bafed7).
[INFO Tue Nov 21 07:32:58 2023]: Logged in as R34!
2023-11-21 07:33:11 ERROR    discord.ext.commands.bot Ignoring exception in command help
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samru\Downloads\main.py", line 254, in help
    embed.set_author(name=f'{ctx.author.display_name}', icon_url=f'{ctx.author.avatar_url}')
                                                                    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Member' object has no attribute 'avatar_url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Python312\Lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Member' object has no attribute 'avatar_url'

**Comment by samalzpro49** [comment]
Just fixed the &help command i i just realized that this bot tries to use discord.py 1.0 and i have to change ctx.author.avatar_url to
ctx.author.avatar.url

**Comment by whitetrashyt** [comment]
Thanks, will rewrite the code within the next 1-2 weeks.
